services:
  nextjs:
    container_name: nextjs
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - "./bbmp:/app"
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:13
    env_file: "./bbmp/.env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
